setName("Clipboard API");
setId("clipboard");
setVersion("1.0");
setDescription("A simple plugin to get Clipboard content");
setAuthor("langyo");
setCollaborators([]);
setUrl("https://www.github.com/langyo/MCBBS-Client");
setServerUrl(url);
setUpdateUrl(url);
setPluginMainclass("net.mcbbs.client.plugin.clipboard.TestPlugin");